default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: c9
  username: ubuntu
  password: ubuntu
  template: template0
  host: <%=ENV['IP']%>

test:
  <<: *default
  database: c9_test
  username: ubuntu
  password: ubuntu
  template: template0
  host: <%=ENV['IP']%>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
